---
#https://ansible.readthedocs.io/projects/builder/en/stable/definition/
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

dependencies:
  python:
    - ansible-tower-cli
    - requests
    - jmespath
  system:
    - hostname
    - jq
    - rsync
    - powershell
  galaxy:
    collections:
      - name: community.vmware
        version: 3.5.0
      - name: community.general
        version: 6.5.0

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: files # copy contents from files to configs dir in build context
    dest: configs

additional_build_steps:
  #prepend_galaxy:
    # reference the file from build context like this
    #- COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  prepend_final:
    - COPY _build/configs/microsoft.repo  /etc/yum.repos.d/microsoft.repo
    - RUN microdnf repolist
  append_final:
    - ls -ld /opt/microsoft/powershell/7/pwsh  && \
    - /bin/pwsh -c 'Set-PSRepository -Name PSGallery -InstallationPolicy Trusted' && \
    - /bin/pwsh -c 'Install-Module VMware.PowerCLI' && \
    - /bin/pwsh -c 'Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Scope AllUsers -Confirm:$False' && \
    - /bin/pwsh -c 'Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $true -Confirm:$False'

